
--PART :: A

CREATE TABLE EMP(
	EID INT,
	ENAME VARCHAR(25),
	DEPARTMENT VARCHAR(25),
	SALARY DECIMAL(10,2),
	JOININGDATE DATE,
	CITY VARCHAR(50),
	GENDER VARCHAR(10)
)
INSERT INTO EMP 
VALUES
(101,'RAHUL','ADMIN',56000,'1990-JAN-01','RAJKOT', 'MALE'),
(102,'HARDIK','IT',18000,'1990-SEP-25','AHMEDABAD', 'MALE'),
(103,'BHAVIN','HR',25000,'1991-MAY-14','BARODA', 'MALE'),
(104,'BHOOMI','ADMIN',39000,'1991-FEB-08','RAJKOT', 'FEMALE'),
(105,'ROHIT','IT',17000,'1990-JUL-23','JAMNAGAR', 'MALE'),
(106,'PRIYA','IT',9000,'1990-OCT-18','AHMEDABAD', 'FEMALE'),
(107,'BHOOMI','HR',34000,'1991-DEC-25','RAJKOT', 'FEMALE')
SELECT * FROM EMP

--1.
SELECT MAX(SALARY) as 'MAX SALARY',MIN(SALARY) as 'MIN SALARY' from EMP
--2.
SELECT SUM(SALARY) AS 'TOTAL_SALARY',AVG(SALARY) AS 'AVERAGE_SALARY' FROM EMP
--3.
SELECT COUNT(EID) AS 'TOTAL EMPLOYEES' FROM EMP
--4.SELECT MAX(SALARY) AS 'MAX SALARY' FROM EMP WHERE CITY='RAJKOT'--5.SELECT MAX(SALARY) AS 'MAX SALARY' FROM EMP WHERE DEPARTMENT='IT'--6.SELECT COUNT(EID) AS 'AFTER_JOINED_08-02-1991' FROM EMP WHERE JOININGDATE>'1991-02-08'--7.SELECT AVG(SALARY) AS 'AVERAGE SALARY' FROM EMP WHERE DEPARTMENT='ADMIN'--8.SELECT SUM(SALARY) AS 'TOTAL SALARY' FROM EMP WHERE DEPARTMENT='HR'--9.SELECT   COUNT(DISTINCT CITY) AS 'CITIES' FROM EMP--10.SELECT   COUNT(DISTINCT DEPARTMENT) AS 'DEPARTMENT TYPES' FROM EMP--11.SELECT   MIN(SALARY) AS 'MIN SALARY' FROM EMP WHERE CITY='AHMEDABAD'--12.SELECT CITY,MAX(SALARY) AS 'MAX SALARY' FROM EMP GROUP BY CITY--13.SELECT DEPARTMENT,MIN(SALARY) AS 'MIN SALARY' FROM EMP GROUP BY DEPARTMENT--14.SELECT CITY,COUNT(EID) AS 'EMPLOYEE' FROM EMP GROUP BY CITY--15.SELECT DEPARTMENT,SUM(SALARY) AS 'TOTAL SALARY' FROM EMP GROUP BY DEPARTMENT--16.SELECT AVG(SALARY) AS 'AVERAGE SALARY' FROM EMP GROUP BY DEPARTMENT--17.SELECT DISTINCT DEPARTMENT, CITY, COUNT(EID) AS 'EMPLOYEE' FROM EMP GROUP BY CITY, DEPARTMENT--18.SELECT GENDER, SUM(SALARY) AS 'TOTAL SALARY' FROM EMP GROUP BY GENDER--19.SELECT CITY, MAX(SALARY) AS 'MAX SALARY', MIN(SALARY) AS 'MIN SALARY' FROM EMP WHERE GENDER='FEMALE' GROUP BY CITY --20.SELECT DEPARTMENT, CITY, GENDER, AVG(SALARY) AS 'AVERAGE SALARY' FROM EMP GROUP BY DEPARTMENT, CITY, GENDER--PART :: B--1.SELECT COUNT(EID) AS 'RAJKOT' FROM EMP WHERE CITY='RAJKOT'--2.SELECT MAX(SALARY)-MIN(SALARY) AS 'SALARY DIFFERENCE' FROM EMP--3.SELECT COUNT(EID) AS 'BEFORE_JOINED_01-01-1991' FROM EMP WHERE JOININGDATE<'1991-01-01'--PART :: C--1.SELECT COUNT(EID) AS 'EMPLOYEE' FROM EMP WHERE CITY = 'RAJKOT' OR CITY = 'BARODA'--2.SELECT COUNT(EID) AS 'BEFORE_JOINED_01-01-1991' FROM EMP WHERE DEPARTMENT = 'IT' AND JOININGDATE<'1991-01-01'--3.SELECT JOININGDATE,SUM(SALARY) AS 'TOTAL SALARY' FROM EMP GROUP BY JOININGDATE--4.SELECT DEPARTMENT, CITY, MAX(SALARY) AS 'MAX SALARY' FROM EMP WHERE CITY LIKE 'R%' GROUP BY DEPARTMENT,CITY