
CREATE TABLE STU_INFO
(
	RNO INT PRIMARY KEY,
	NAME VARCHAR(50),
	BRANCH VARCHAR(50)
)
INSERT INTO STU_INFO
VALUES
(101,'RAJU','CE'),
(102,'AMIT','CE'),
(103,'SANJAY','ME'),
(104,'NEHA','EC'),
(105,'MEERA','EE'),
(106,'MAHESH','ME')
SELECT * FROM STU_INFO

CREATE TABLE RESULT
(
	RNO INT FOREIGN KEY REFERENCES STU_INFO(RNO),
	SPI DECIMAL(8,2)
)
INSERT INTO RESULT
VALUES
(101,8.8),
(102,9.2),
(103,7.6),
(104,8.2),
(105,7.0)
--(107,8.9)
SELECT *  FROM RESULT

CREATE TABLE EMPLOYEE_DETAILS --(EMPLOYEE_MASTER)--
(
	EMPLOYEENO VARCHAR(50),
	NAME VARCHAR(50),
	MANAGERNO VARCHAR(50)
)
INSERT INTO EMPLOYEE_DETAILS
VALUES
('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')
SELECT * FROM EMPLOYEE_DETAILS



--Part :: A 
--1.
iSELECT * FROM STU_INFO S CROSS JOIN RESULT R
--2.
SELECT * FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO
--3.
SELECT * FROM STU_INFO S LEFT OUTER JOIN RESULT R ON S.RNO = R.RNO
--4.
SELECT * FROM STU_INFO S RIGHT OUTER JOIN RESULT R ON S.RNO = R.RNO
--5.
SELECT * FROM STU_INFO S FULL OUTER JOIN RESULT R ON S.RNO = R.RNO
--6.
SELECT S.RNO , S.NAME , S.BRANCH , R.SPI FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO
--7.
SELECT S.RNO , S.NAME , S.BRANCH , R.SPI FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO WHERE S.BRANCH = 'CE'
--8.
SELECT S.RNO , S.NAME , S.BRANCH , R.SPI FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO WHERE S.BRANCH != 'EC'
--9.
SELECT S.BRANCH , AVG(R.SPI) FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO GROUP BY S.BRANCH
--10.
SELECT S.BRANCH , AVG(R.SPI) FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO GROUP BY S.BRANCH HAVING S.BRANCH = 'CE' OR S.BRANCH = 'ME'
--11.
SELECT S.BRANCH , MIN(R.SPI) AS 'MIN' , MAX(R.SPI) AS 'MAX' FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO GROUP BY S.BRANCH
--12.
SELECT S.BRANCH , COUNT(R.RNO) FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO GROUP BY S.BRANCH ORDER BY COUNT(R.RNO) DESC



--Part :: B 
--1.
SELECT S.BRANCH , AVG(R.SPI) FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO GROUP BY S.BRANCH ORDER BY AVG(R.SPI)
--2.
SELECT S.BRANCH , MAX(R.SPI) FROM STU_INFO S INNER JOIN RESULT R ON S.RNO = R.RNO GROUP BY S.BRANCH ORDER BY MAX(R.SPI)



--Part :: C 
--1.
SELECT E1.NAME AS 'Employee' , E.NAME AS 'Manager' FROM EMPLOYEE_DETAILS E RIGHT OUTER JOIN EMPLOYEE_DETAILS E1 ON E.EMPLOYEENO = E1.MANAGERNO