CREATE TABLE CUSTOMERS_EH
(
	CUS_ID INT PRIMARY KEY,
	CUS_NAME VARCHAR(250) NOT NULL,
	CUS_EMAIL VARCHAR(50) UNIQUE
)	

CREATE TABLE ORDERS_EH
(
	ORDER_ID INT PRIMARY KEY,
	CUS_ID INT FOREIGN KEY REFERENCES CUSTOMERS_EH(CUS_ID),
	ORDER_DATE DATE NOT NULL
)

