USE DBMS

-- UPDATE

-- PART :: A
-- 1.
UPDATE DEPOSIT SET AMOUNT=4000 WHERE AMOUNT BETWEEN 3000 AND 5000
SELECT * FROM DEPOSIT
-- 2.
UPDATE BORROW SET BNAME='C.G. ROAD' WHERE CNAME='ANIL'
SELECT * FROM BORROW
-- 3.
UPDATE DEPOSIT SET ACTNO=111, AMOUNT=5000 WHERE CNAME='SANDIP'
SELECT * FROM DEPOSIT
-- 4.
UPDATE DEPOSIT SET AMOUNT=7000 WHERE CNAME='KRANTI'
SELECT * FROM DEPOSIT
-- 5.
UPDATE BRANCH SET BNAME='ANDHERI WEST' WHERE BNAME='ANDHERI'
SELECT * FROM BRANCH
-- 6.
UPDATE DEPOSIT SET BNAME='NEHRU PLACE' WHERE CNAME='MEHUL'
SELECT * FROM DEPOSIT
-- 7.UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO BETWEEN 103 AND 107SELECT * FROM DEPOSIT-- 8.UPDATE DEPOSIT SET ADATE='1995-04-01' WHERE CNAME='ANIL'SELECT * FROM DEPOSIT-- 9.UPDATE DEPOSIT SET AMOUNT=10000 WHERE CNAME='MINU'SELECT * FROM DEPOSIT-- 10.UPDATE DEPOSIT SET AMOUNT=5000, ADATE='1996-04-01' WHERE CNAME='PRAMOD'SELECT * FROM DEPOSIT--PART :: B-- 1.SELECT *,AMOUNT=AMOUNT*1.10 FROM BORROWUPDATE BORROW SET AMOUNT=AMOUNT*1.10-- 2.SELECT *, AMOUNT=AMOUNT*1.10 FROM DEPOSITUPDATE DEPOSIT SET AMOUNT=AMOUNT*1.10-- 3.SELECT *, AMOUNT=AMOUNT+1000 FROM DEPOSITUPDATE DEPOSIT SET AMOUNT=AMOUNT+1000-- 4.UPDATE BORROW SET AMOUNT=7000, BNAME='CENTRAL' WHERE CNAME='MEHUL' AND LOANNO %2=0SELECT * FROM BORROW-- 5.UPDATE DEPOSIT SET ADATE='2022-05-15', AMOUNT=2500 WHERE BNAME='VRCE' AND ACTNO<105-- PART :: C-- 1.UPDATE BORROW SET AMOUNT=NULL WHERE LOANNO=321-- 2.UPDATE BORROW SET BNAME=NULL WHERE BNAME='KRANTI'-- 3.SELECT CNAME FROM BORROW WHERE LOANNO IS NULL-- 4.SELECT CNAME FROM BORROW WHERE NOT BNAME IS NULL-- 5.UPDATE BORROW SET AMOUNT=5000, BNAME='VRCE', CNAME='DARSHAN' WHERE LOANNO=481-- 6.UPDATE DEPOSIT SET ADATE='2021-01-01' WHERE AMOUNT<2000-- 7.UPDATE DEPOSIT SET ADATE=NULL, BNAME='ANDHERI' WHERE ACTNO=110-- ALTER & RENAME-- PART :: A-- 1.ALTER TABLE DEPOSIT ADD CITY VARCHAR(20),PINCODE INT-- 2.ALTER TABLE DEPOSIT ADD STTATE VARCHAR(20)-- 3.ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)-- 4.ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT-- 5.ALTER TABLE DEPOSIT DROP COLUMN CITY-- 6.EXEC sp_rename 'DEPOSIT.ACTNO', 'ANO', 'COLUMN'-- 7.EXEC sp_rename 'DEPOSIT', 'DEPOSIT_DETAILS'-- PART :: B-- 1.EXEC sp_rename 'DEPOSIT_DETAIL.ADATE', 'AOPENDATE', 'COLUMN'-- 2.ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE-- 3.EXEC sp_rename 'DEPOSIT_DETAIL.CNAME', 'CustomerName', 'COLUMN'-- 4.ALTER TABLE DEPOSIT_DETAIL ADD COUNTRY VARCHAR(20)-- PART :: CCREATE TABLE STUDENT_DETAIL(	ENROLLMENT_NO VARCHAR(20),	S_NAME VARCHAR(25),	CPI DECIMAL(5,2),	BIRTHDATE DATETIME)-- 1.ALTER TABLE STUDENT_DETAIL ADD City VARCHAR(20) NOT NULL, BACKLOG INT-- 2.ALTER TABLE STUDENT_DETAIL ADD department VARCHAR(20) NOT NULL-- 3.ALTER TABLE STUDENT_DETAIL ALTER COLUMN S_Name VARCHAR(35)-- 4.ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT-- 5.ALTER TABLE STUDENT_DETAIL DROP COLUMN City-- 6.EXEC sp_rename 'STUDENT_DETAIL.Enrollment_No', 'ENO', 'COLUMN'-- 7.EXEC sp_rename 'STUDENT_DETAIL', 'STUDENT_MASTER'-- DELETE & TRUNCATE & DROP-- PART :: A-- 1.DELETE DEPOSIT WHERE AMOUNT<=4000-- 2.DELETE DEPOSIT WHERE BNAME='CHANDI'-- 3.DELETE DEPOSIT WHERE ACTNO BETWEEN 102 AND 105-- 4.DELETE DEPOSIT WHERE BNAME IN ('AJNI','POWAI')-- 5.DELETE DEPOSIT WHERE ACTNO IS NULL-- 6.DELETE DEPOSIT_DETAILS-- 7.TRUNCATE TABLE DEPOSIT_DETAILS-- 8.DROP TABLE DEPOSIT_DETAILS-- PART :: BCREATE TABLE EMPLOYEE_MASTER(	EMPNO INT,	EMPNAME VARCHAR(25),	JOININGDATE DATE,	SALARY DECIMAL(8,2),	CITY VARCHAR(20))INSERT INTO EMPLOYEE_MASTER VALUES(101,'KEYUR','2002-01-05',12000.00,'RAJKOT'),(102,'HARDIK','2004-02-15',14000.00,'AHMEDABAD'),(103,'KAJAL','2006-03-14',15000.00,'BARODA'),(104,'BHOOMI','2005-06-23',12500.00,'AHMEDABAD'),(105,'HARMIT','2004-02-15',14000.00,'RAJKOT'),(106,'MITESH','2001-09-25',5000.00,'JAMNAGAR'),(107,'MEERA',NULL,7000.00,'MORBI'),(108,'KISHAN','2003-02-06',10000.00,NULL)SELECT * FROM EMPLOYEE_MASTER-- 1.DELETE EMPLOYEE_MASTER WHERE Salary>=14000-- 2.DELETE EMPLOYEE_MASTER WHERE City='Rajkot'-- 3.DELETE EMPLOYEE_MASTER WHERE JoiningDate>'2007-01-01'-- 4.DELETE EMPLOYEE_MASTER WHERE JoiningDate=NULL AND EmpName!=NULL-- 5.DELETE EMPLOYEE_MASTER WHERE Salary=20000/1.50-- 6.DELETE EMPLOYEE_MASTER WHERE City!=NULL-- 7.TRUNCATE TABLE EMPLOYEE_MASTER-- 8.DROP TABLE EMPLOYEE_MASTER-- PART :: C-- 1.