USE DBMS

CREATE TABLE SALES_DATA(
	REGION VARCHAR(25),
	PRODUCT VARCHAR(25),
	SALES_AMOUNT DECIMAL(10,2),
	YEAR INT
)

INSERT INTO SALES_DATA 
VALUES
('NORTH AMERICA','WATCH',1500,2023),
('EUROPE','MOBILE',1200,2023),
('ASIA','WATCH',1800,2023),
('NORTH AMERICA','TV',900,2024),
('EUROPE','WATCH',2000,2024),
('ASIA','MOBILE',1000,2024),
('NORTH AMERICA','MOBILE',1600,2023),
('EUROPE','TV',1500,2023),
('ASIA','TV',1100,2024),
('NORTH AMERICA','WATCH',1700,2024)

SELECT * FROM SALES_DATA


--PART :: A
--1.
SELECT REGION , SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION
--2.
SELECT PRODUCT , AVG(SALES_AMOUNT) FROM SALES_DATA GROUP BY PRODUCT
--3.
SELECT YEAR , MAX(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR
--4.
SELECT REGION , YEAR , MIN(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION , YEAR
--5.
SELECT REGION , COUNT(PRODUCT) FROM SALES_DATA GROUP BY REGION
--6.
SELECT YEAR , PRODUCT , SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR , PRODUCT
--7.
SELECT REGION , SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION HAVING SUM(Sales_Amount) > 5000
--8.
SELECT PRODUCT , AVG(SALES_AMOUNT) FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(Sales_Amount) < 10000
--9.
SELECT YEAR , MAX(Sales_Amount) FROM SALES_DATA GROUP BY YEAR HAVING MAX(SALES_AMOUNT) > 500
--10.
SELECT COUNT(DISTINCT PRODUCT) , REGION FROM SALES_DATA GROUP BY REGION HAVING COUNT(DISTINCT PRODUCT) >= 3
--11.
SELECT YEAR , MIN(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR HAVING MIN(SALES_AMOUNT) < 1000 
--12.
SELECT REGION , YEAR , SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION , YEAR
--13.
SELECT REGION , MIN(SALES_AMOUNT) FROM SALES_DATA WHERE PRODUCT = 'MOBILE' GROUP BY REGION
--14.
SELECT DISTINCT REGION , PRODUCT , MAX(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR = 2023 GROUP BY PRODUCT , REGION
--15.
SELECT REGION , SUM(SALES_AMOUNT) FROM SALES_DATA WHERE PRODUCT = 'TV' AND YEAR = 2023 GROUP BY REGION HAVING SUM(Sales_Amount) > 1000



--PART :: B
--1.
SELECT REGION , YEAR , COUNT(PRODUCT) FROM SALES_DATA GROUP BY REGION , YEAR
--2.
SELECT REGION , MAX(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION HAVING MAX(SALES_AMOUNT) > 1000 ORDER BY REGION
--3.
SELECT YEAR , SUM(SALES_AMOUNT) FROM SALES_DATA GROUP BY YEAR HAVING SUM(SALES_AMOUNT) < 10000 ORDER BY YEAR DESC
--4.
SELECT TOP 3 REGION , SUM(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR = 2024 GROUP BY REGION
--5.
SELECT TOP 1 REGION , YEAR , MIN(SALES_AMOUNT) FROM SALES_DATA GROUP BY REGION , YEAR



--PART :: C
--1.
SELECT PRODUCT , AVG(SALES_AMOUNT) FROM SALES_DATA GROUP BY PRODUCT HAVING AVG(SALES_AMOUNT) BETWEEN 1000 AND 2000 ORDER BY PRODUCT
--2.
SELECT YEAR , REGION FROM SALES_DATA GROUP BY YEAR , REGION HAVING COUNT(PRODUCT) > 1
--3.
SELECT REGION , AVG(SALES_AMOUNT) FROM SALES_DATA WHERE YEAR = 2023 GROUP BY REGION HAVING AVG(SALES_AMOUNT) > 1500 ORDER BY AVG(SALES_AMOUNT) DESC
--4.
SELECT REGION , COUNT(PRODUCT) FROM SALES_DATA GROUP BY REGION
--5.
SELECT YEAR , COUNT(PRODUCT) FROM SALES_DATA GROUP BY YEAR