CREATE TABLE PERSON_INFO(
	P_ID INT PRIMARY KEY,
	P_NAME VARCHAR(100) NOT NULL,
	P_SALARY DECIMAL(8,2) NOT NULL,
	P_JOINING_DATE DATETIME,
	P_CITY VARCHAR(100) NOT NULL,
	P_AGE INT,
	P_DOB Date NOT NULL
)

CREATE TABLE PERSON_LOG(
	PLOG_ID INT PRIMARY KEY IDENTITY(1,1),
	P_ID INT NOT NULL,
	P_NAME NVARCHAR(100) NOT NULL,
	OPERATION VARCHAR(50) NOT NULL,
	UPDATEDATE DATETIME NOT NULL
)


-- PART A:
-- 1.
CREATE TRIGGER INS_DEL_UPD
ON PERSON_INFO
FOR INSERT,UPDATE,DELETE
AS
BEGIN
	PRINT 'RECORD AFFECTED'
END

-- INSERT QUERY --
INSERT INTO PERSON_INFO VALUES
(101,'JOHN',250000,'2020-05-20','RAJKOT',20,'2006-11-20')
-- UPDATE QUERY --
UPDATE PERSON_INFO SET P_NAME = 'NEEL' WHERE P_ID=101
-- DELETE QUERY --
DELETE FROM PERSON_INFO WHERE P_ID=101

-- 2.
CREATE TRIGGER PERSON_INSERTED
ON PERSON_INFO
FOR INSERT,UPDATE
AS
BEGIN
	DECLARE @PID INT,@PNAME VARCHAR(250)
	SELECT @PID = P_ID FROM INSERTED
	SELECT @PNAME = P_NAME FROM INSERTED
	INSERT INTO PERSON_LOG VALUES(@PID,@PNAME,ERROR_MESSAGE(),GETDATE())
END


CREATE TRIGGER PSERONS_DELETED
ON PERSON_INFO
FOR DELETE
AS
BEGIN
	DECLARE @PID INT,@PNAME VARCHAR(250)
	SELECT @PID = P_ID FROM DELETED
	SELECT @PNAME = P_NAME FROM DELETED
	INSERT INTO PERSON_LOG VALUES(@PID,@PNAME,ERROR_MESSAGE(),GETDATE())
END

SELECT * FROM PERSON_INFO
