
-- PART :: A
CREATE TABLE STUDENT
(
	STUID INT,
	FIRSTNAME VARCHAR(25),
	LASTNAME VARCHAR(25),
	WEBSITE VARCHAR(50),
	CITY VARCHAR(25),
	ADDRESS VARCHAR(100)
)
INSERT INTO STUDENT 
VALUES
(1011,'KEYUR','PATEL','TECHONTHENET.COM','RAJKOT','A-303 "VASANT KUNJ", RAJKOT'),
(1022,'HARDIK','SHAH','DIGMINECRAFT.COM','AHMEDABAD','"RAM KRUPA", RAIYA ROAD'),
(1033,'KAJAL','TRIVEDI','BIGACTIVITIES.COM','BARODA','RAJ BHAVAN PLOT,NEAR GARDEN'),
(1044,'BHOOMI','GAJERA','CHECKYOURMATH.COM','AHMEDABAD','"JIG`S HOME", NAROL'),
(1055,'HARMIT','MITEL','@ME.DARSHAN.COM','RAJKOT','B-55, RAJ RESIDENCY'),
(1066,'ASHOK','JAIN',NULL,'BARODA','A502, CLUB HOUSE BUILDING')
SELECT * FROM STUDENT
--1.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('K%')
--2.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('_____')
--3.
SELECT FIRSTNAME,LASTNAME FROM STUDENT WHERE CITY LIKE ('_____A')
--4.
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE ('%TEL')
--5.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('HA%T')
--6.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('K_Y%')
--7.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('_____') AND WEBSITE IS NULL
--8.
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE ('%JER%')
--9.
SELECT FIRSTNAME FROM STUDENT WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'
--10.
SELECT FIRSTNAME FROM STUDENT WHERE WEBSITE IS NOT NULL
--11.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('[A-H]%')
--12.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('_[A,E,I,O,U]%')
--13.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('_____%') AND WEBSITE IS NULL
--14.
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE ('PAT%')
--15.
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME NOT LIKE ('B%')
--16.
SELECT FIRSTNAME FROM STUDENT WHERE STUID LIKE ('%[0-9]')
--17.
SELECT FIRSTNAME FROM STUDENT WHERE ADDRESS NOT LIKE ('%[0-9]%')
--18.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('B%') AND LASTNAME LIKE ('%A') And WEBSITE LIKE ('%[MATH,SCIENCE]%') AND CITY NOT LIKE ('B%')
--19.
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME LIKE ('SHAH') AND CITY LIKE ('%D') AND WEBSITE LIKE ('%[NULL,COM]%')
--20.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('[A,E,I,O,U][A,E,I,O,U]%') AND CITY LIKE ('R%') AND WEBSITE LIKE ('%.COM%')



--PART :: B
--1.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME LIKE ('H[A,E,I,O,U]%')
--2.
SELECT FIRSTNAME FROM STUDENT WHERE LASTNAME NOT LIKE ('%A')
--3.
SELECT FIRSTNAME FROM STUDENT WHERE FIRSTNAME NOT LIKE ('[A,E,I,O,U]%')
--4.
SELECT * FROM STUDENT WHERE FIRSTNAME LIKE ('K%') AND LASTNAME LIKE ('%TEL') And WEBSITE LIKE ('%TECH%') OR CITY LIKE ('R%')
--5.
SELECT * FROM STUDENT WHERE ADDRESS LIKE ('%-%') AND CITY LIKE ('[R,B]%') AND WEBSITE LIKE ('%.COM%') AND FIRSTNAME NOT LIKE ('A%')



--PART :: C
--1.
SELECT * FROM STUDENT WHERE ADDRESS LIKE ('%[""'']%')
--2.
SELECT * FROM STUDENT WHERE CITY NOT LIKE ('%S%') AND ADDRESS LIKE ('%[""'']%') AND LASTNAME LIKE ('P%') AND WEBSITE LIKE ('%ON%')