USE DBMS

CREATE TABLE PERSON_DATA
(
	PERSONID INT PRIMARY KEY IDENTITY(101,1),
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	SALARY DECIMAL(8,2) NOT NULL,
	JOININGDATE DATE NOT NULL,
	DEPARTMENTID INT FOREIGN KEY REFERENCES DEPARTMENT_DATA(DEPARTMENTID),
	DESIGNATIONTID INT FOREIGN KEY REFERENCES DESIGNATION(DESIGNATIONTID)
)
INSERT INTO PERSON_DATA VALUES 
('RAHUL','ANSHU',56000,'1990-01-01',1,12),
('HARDIK','HINSU',18000,'1990-09-25',2,11),
('BHAVIN','KAMANI',25000,'1991-05-14',NULL,11),
('BHOOMI','PATEL',39000,'2014-02-20',1,13),
('ROHIT','RAJGOR',17000,'1990-07-23',2,15),
('PRIYA','MEHTA',25000,'1990-10-18',2,NULL),
('NEHA','TRIVEDI',18000,'2014-02-20',3,15)
SELECT * FROM PERSON_DATA
CREATE TABLE DEPARTMENT_DATA
(
	DEPARTMENTID INT PRIMARY KEY,
	DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE,
)
INSERT INTO DEPARTMENT_DATA
VALUES
(1,'ADMIN'),
(2,'IT'),
(3,'HR'),
(4,'ACCOUNT')
SELECT * FROM DEPARTMENT_DATA
CREATE TABLE DESIGNATION
(
	DESIGNATIONTID INT PRIMARY KEY,
	DESIGNATIONNAME VARCHAR(100) NOT NULL UNIQUE,
)
INSERT INTO DESIGNATION
VALUES
(11,'JOBBER	'),
(12,'WELDER'),
(13,'CLERK'),
(14,'MANAGER'),
(15,'CEO')
SELECT * FROM DESIGNATION


-- PART :: A
-- 1.
-- DEPARTMENT_DATA
CREATE PROC DEPARTMENT_INSERT_UPDATE_DELETE
@DEPT_ID INT , @DEPT_NAME VARCHAR
AS
BEGIN
	INSERT INTO DEPARTMENT_DATA VALUES ( @DEPT_ID , @DEPT_NAME )
	UPDATE DEPARTMENT_DATA SET DEPARTMENTNAME = @DEPT_NAME WHERE DEPARTMENTID = @DEPT_ID
	DELETE FROM DEPARTMENT_DATA WHERE DEPARTMENTID = @DEPT_ID
END
-- DESIGNATION
CREATE PROC DESIGNATION_INSERT_UPDATE_DELETE
@DES_ID INT , @DES_NAME VARCHAR
AS
BEGIN
	INSERT INTO DESIGNATION VALUES ( @DES_ID , @DES_NAME )
	UPDATE DESIGNATION SET DESIGNATIONNAME = @DES_NAME WHERE DESIGNATIONTID = @DES_ID
	DELETE FROM DESIGNATION WHERE DESIGNATIONTID = @DES_ID
END
--  PERSON
CREATE PROC PERSON_INSERT_UPDATE_DELETE 
@PID INT , @PFNAME VARCHAR , @PLNAME VARCHAR , @PSALARY DECIMAL(8,2) , @PDATE DATE , @DEPTID INT ,
@DESID INT
AS
BEGIN
	INSERT INTO PERSON_DATA VALUES ( @PFNAME , @PLNAME , @PSALARY , @PDATE , @DEPTID , @DESID )
	UPDATE PERSON_DATA SET FIRSTNAME = @PFNAME WHERE PERSONID = @PID
	DELETE FROM PERSON_DATA WHERE PERSONID = @PID
END

-- 2.
-- DEPARTMENT
CREATE PROC DEPARTMENT_SELECT_PRIMARYKEY
@DEPT_ID INT
AS
BEGIN
	SELECT * FROM DEPARTMENT_DATA WHERE DEPARTMENTID = @DEPT_ID
END
-- DESIGNATION
CREATE PROC DESIGNATION_SELECT_PRIMARYKEY
@DES_ID INT
AS
BEGIN
	SELECT * FROM DESIGNATION WHERE DESIGNATIONTID = @DES_ID
END
-- PERSON
CREATE PROC PERSON_SELECT_PRIMARYKEY
@PID INT
AS
BEGIN
	SELECT * FROM PERSON_DATA WHERE PERSONID = @PID
END

-- 3.
CREATE PROC DEPARTMENT_DESIGNATION_PERSON_JOIN
AS
BEGIN
	SELECT * FROM 
	PERSON_DATA PER JOIN DEPARTMENT_DATA DEPT ON PER.DEPARTMENTID = DEPT.DEPARTMENTID
	JOIN DESIGNATION DES ON PER.DESIGNATIONTID = DES.DESIGNATIONTID
END

-- 4.
CREATE PROC DEPARTMENT_DESIGNATION_PERSON_SELECT
AS
BEGIN
	SELECT TOP 3 * FROM PERSON_DATA
	SELECT TOP 3 * FROM DEPARTMENT_DATA
	SELECT TOP 3 * FROM DESIGNATION
END

EXEC DEPARTMENT_DESIGNATION_PERSON_SELECT



SELECT * FROM PERSON_DATA
SELECT * FROM DEPARTMENT_DATA
-- PART :: B

-- 1.
CREATE PROC ALL_WORKER
@DNAME VARCHAR(100)
AS
BEGIN
	SELECT * FROM PERSON_DATA WHERE DEPARTMENTID = 
	(SELECT DEPARTMENTID FROM DEPARTMENT_DATA WHERE DEPARTMENTNAME = @DNAME)
END

-- 2.
ALTER PROC ALL_WORKER_DETAILS
@DNAME VARCHAR(100) , @DESNAME VARCHAR(100)
AS
BEGIN
	SELECT FIRSTNAME , SALARY , JOININGDATE , @DNAME AS 'DEPARTMENTNAME' FROM PERSON_DATA WHERE DEPARTMENTID = 
	(SELECT DEPARTMENTID FROM DEPARTMENT_DATA WHERE DEPARTMENTNAME = @DNAME) AND DESIGNATIONTID =
	(SELECT DESIGNATIONTID FROM DESIGNATION WHERE DESIGNATIONNAME = @DESNAME)
END

-- 3.
CREATE PROC PERSON_DETAILS
@FNAME VARCHAR(100)
AS
BEGIN
	SELECT PER.* , DEPT.DEPARTMENTNAME , DES.DESIGNATIONNAME FROM PERSON_DATA PER 
	JOIN DEPARTMENT_DATA DEPT ON PER.DEPARTMENTID = DEPT.DEPARTMENTID
	JOIN DESIGNATION DES ON PER.DESIGNATIONTID = DES.DESIGNATIONTID
	WHERE FIRSTNAME = @FNAME
END

-- 4.
CREATE PROC MAX_MIN_TOTAL_SALARY
AS
BEGIN
	SELECT DEPARTMENTID , MAX(SALARY) AS 'MAX' , MIN(SALARY) AS 'MIN' , SUM(SALARY) AS 'TOTAL' FROM PERSON_DATA GROUP BY DEPARTMENTID
END

-- 5.
CREATE PROC AVG_TOTAL_SALARY
AS
BEGIN
	SELECT DESIGNATIONTID , AVG(SALARY) AS 'AVG' , SUM(SALARY) AS 'TOTAL' FROM PERSON_DATA GROUP BY DESIGNATIONTID
END



-- PART :: C

-- 1.
CREATE PROC PERSON_COUNT
@DNAME VARCHAR(100)
AS
BEGIN
	SELECT COUNT(PERSONID) FROM PERSON_DATA WHERE DEPARTMENTID = (SELECT DEPARTMENTID FROM DEPARTMENT_DATA WHERE DEPARTMENTNAME = @DNAME)
END

-- 2.
CREATE PROC ALL_DETAILS_FROM_SALARY
@SALARY DECIMAL(8,2)
AS
BEGIN
	SELECT PER.* , DEPT.* , DES.* FROM PERSON_DATA PER 
	JOIN DEPARTMENT_DATA DEPT ON PER.DEPARTMENTID = DEPT.DEPARTMENTID 
	JOIN DESIGNATION DES ON PER.DESIGNATIONTID = DES.DESIGNATIONTID
	WHERE PER.SALARY > @SALARY
END

-- 3.
CREATE PROC MAX_SALARY_DEPARTMENT
AS
BEGIN
	SELECT TOP 1 DEPT.DEPARTMENTNAME , MAX(PER.SALARY) FROM PERSON_DATA PER 
	JOIN DEPARTMENT_DATA DEPT ON PER.DEPARTMENTID = DEPT.DEPARTMENTID
	GROUP BY DEPT.DEPARTMENTNAME
END

-- 4.
CREATE PROC ALL_WORKERS
@DNAME VARCHAR(100)
AS
BEGIN
	SELECT PER.* , DEPT.* , DES.* FROM PERSON_DATA PER JOIN DEPARTMENT_DATA DEPT ON PER.DEPARTMENTID = DEPT.DEPARTMENTID 
	JOIN DESIGNATION DES ON PER.DESIGNATIONTID = DES.DESIGNATIONTID WHERE DES.DESIGNATIONNAME = @DNAME
	AND PER.JOININGDATE <= DATEADD(YEAR , 10 , GETDATE())
END
-- 5.
CREATE PROCEDURE WORKER_WITHOUT_DES
AS
BEGIN
    SELECT DEPT.DEPARTMENTNAME , COUNT(PER.PERSONID) FROM PERSON_DATA PER
    JOIN DEPARTMENT_DATA DEPT ON PER.DEPARTMENTID = DEPT.DEPARTMENTID WHERE PER.DESIGNATIONTID IS NULL
    GROUP BY DEPT.DEPARTMENTNAME
END
-- 6.
CREATE PROCEDURE WORKERS_AVG_SALARY_12000
AS
BEGIN
    SELECT PER.PERSONID, PER.FIRSTNAME,PER.LASTNAME,PER.SALARY,PER.JOININGDATE,DEPT.DEPARTMENTNAME,DES.DESIGNATIONNAM FROM PERSON_DATA PER 
	JOIN DEPARTMENT_DATA DEPT ON PER.DEPARTMENTID = DEPT.DEPARTMENTID JOIN DESIGNATION DES ON PER.DESIGNATIONTID = DES.DESIGNATIONTID
    WHERE PER.DEPARTMENTID IN (SELECT DEPARTMENTID FROM PERSON_DATA GROUP BY DEPARTMENTID HAVING AVG(SALARY) > 12000)
END
