

CREATE TABLE DEPT
(
	DEPARTMENTID INT PRIMARY KEY,
	DEPARTMENTNAME VARCHAR(100) NOT NULL UNIQUE,
	DEPARTMENTCODE VARCHAR(50) NOT NULL UNIQUE,
	LOCATION VARCHAR(50) NOT NULL
)
INSERT INTO DEPT
VALUES
(1,'ADMIN','ADM','A-BLOCK'),
(2,'COMPUTER','CE','C-BLOCK'),
(3,'CIVIL','CI','G-BLOCK'),
(4,'ELECTRICAL','EE','E-BLOCK'),
(5,'MECHANICAL','ME','B-BLOCK')
SELECT * FROM DEPT

CREATE TABLE PERSON
(
	PERSONID INT PRIMARY KEY,
	PERSONNAME VARCHAR(100) NOT NULL,
	DEPARTMENTID INT FOREIGN KEY REFERENCES DEPT(DEPARTMENTID),
	SALARY DECIMAL(8,2) NOT NULL,
	JOININGDATE DATE NOT NULL,
	CITY VARCHAR(100) NOT NULL
)
INSERT INTO PERSON 
VALUES
(101, 'RAHUL TRIPATHI', 2, 56000, '2000-01-01', 'RAJKOT'),
(102, 'HARDIK PANDYA', 3, 18000, '2001-09-25', 'AHMEDABAD'),
(103, 'BHAVIN KANANI ', 4, 25000, '2000-05-14', 'BARODA'),
(104, 'BHOOMI VAISHNAV ', 1, 39000, '2005-02-08', 'RAJKOT'),
(105, 'ROHIT TOPIYA ', 2, 17000, '2001-07-23', 'JAMNAGAR'),
(106, 'PRIYA MENPARA ', NULL, 9000, '2000-10-18', 'AHMEDABAD'),
(107, 'NEHA SHARMA ', 2, 34000, '2002-12-25', 'RAJKOT'),
(108, 'NAYAN GOSWAMI', 3, 25000, '2001-07-01', 'RAJKOT'),
(109, 'MEHUL BHUNDIYA ', 4, 13000, '2005-01-09', 'BARODA'),
(110, 'MOHIT MARU ', 5, 14000, '2000-05-25', 'JAMNAGAR')
SELECT * FROM PERSON



--Part :: A
--1.
SELECT * FROM PERSON CROSS JOIN DEPT
SELECT * FROM PERSON, DEPT
--2.
SELECT P.PERSONNAME, D.DEPARTMENTNAME FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID
--3.
SELECT P.PERSONNAME, D.DEPARTMENTNAME, D.DEPARTMENTCODE FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID
--4.
SELECT P.PERSONNAME, D.DEPARTMENTNAME, D.LOCATION FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID
--5.
SELECT * FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID WHERE D.DEPARTMENTNAME = 'Mechanical'
--6.
SELECT P.PERSONNAME, D.DEPARTMENTCODE, P.SALARY FROM PERSON P LEFT JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID WHERE P.CITY = 'Ahmedabad'
--7.
SELECT P.PERSONNAME FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID  WHERE D.LOCATION = 'C-Block'
--8.
SELECT P.PERSONNAME, P.SALARY, D.DEPARTMENTNAME FROM PERSON P LEFT JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID WHERE P.CITY = 'Jamnagar'
--9.
SELECT * FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID WHERE D.DEPARTMENTNAME = 'Civil' AND P.CITY > '2001-08-01'
--10.
SELECT P.PERSONNAME, D.DEPARTMENTNAME FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID WHERE DATEDIFF(DAY, P.JOININGDATE, GETDATE()) > 365
--11.
SELECT D.DEPARTMENTNAME, COUNT(P.DEPARTMENTID) AS 'Working Employees' FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID GROUP BY D.DEPARTMENTNAME
--12.
SELECT D.DEPARTMENTNAME, MIN(P.SALARY) AS 'Minimum SALARY', MAX(P.SALARY) AS 'Maximum SALARY' FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID GROUP BY D.DEPARTMENTNAME
--13.
SELECT P.CITY, SUM(P.SALARY) AS 'Total SALARY', AVG(P.SALARY) AS 'Average SALARY', MAX(P.SALARY) AS 'Maximum SALARY', MIN(P.SALARY) AS 'Minimum SALARY' FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID GROUP BY P.CITY
--14.
SELECT AVG(SALARY) AS 'Average SALARY' FROM PERSON WHERE CITY = 'Ahmedabad'
--15.
SELECT CONCAT_WS(' ', P.PERSONNAME, 'linves in', P.CITY, 'and works in', D.DEPARTMENTNAME, 'Department.') AS '<PERSONNAME> lives in <CITY> and works in <DEPARTMENTNAME> Department.' FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID



--Part :: B
--1.
SELECT CONCAT_WS(' ', P.PERSONNAME, 'EARNS', P.SALARY, 'FROM', D.DEPARTMENTNAME, 'DEPARTMENT MONTHLY.') AS '<PERSONNAME> EARNS <SALARY> FROM <DEPARTMENTNAME> DEPARTMENT MONTHLY' FROM PERSON P LEFT JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID
--2.
SELECT P.CITY, D.DEPARTMENTNAME, SUM(SALARY) AS 'TOTAL SALARY', AVG(SALARY) AS 'AVRAGE SALARY', MAX(SALARY) AS 'MAXIMUM SALARY' FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID GROUP BY P.CITY, D.DEPARTMENTNAME
--3.
SELECT P.PERSONNAME FROM PERSON P LEFT JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID WHERE P.DEPARTMENTID != D.DEPARTMENTID OR P.DEPARTMENTID IS NULL
--4.
SELECT D.DEPARTMENTNAME FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID GROUP BY D.DEPARTMENTNAME HAVING SUM(P.SALARY) > 10000



--Part :: C

--1.
SELECT D.DEPARTMENTNAME FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID GROUP BY D.DEPARTMENTNAME HAVING COUNT(P.PERSONID) = 0
--2.
SELECT D.DEPARTMENTNAME FROM PERSON P INNER JOIN DEPT D ON P.DEPARTMENTID = D.DEPARTMENTID GROUP BY D.DEPARTMENTNAME HAVING COUNT(P.PERSONID) >= 2
--3.
UPDATE PERSON SET SALARY = SALARY * 0.10 WHERE DEPARTMENTID = (SELECT DEPARTMENTID FROM DEPT WHERE DEPARTMENTNAME = 'Computer')