CREATE TABLE PRODUCTS(
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCT_NAME NVARCHAR(250) NOT NULL,
	PRICE DECIMAL(10,2) NOT NULL,
)

INSERT INTO PRODUCTS VALUES
(1,'SMARTPHONE',35000),
(2,'LAPTOP',65000),
(3,'HEADPHONES',5500),
(4,'TELEVISION',85000),
(5,'GAMING CONSOLE',32000)

SELECT * FROM PRODUCTS

----------------------------------------------------------------------
-- PART A
-- 1.
DECLARE CUR_SELECT CURSOR
FOR SELECT PRODUCT_ID, PRODUCT_NAME,PRICE FROM PRODUCTS
DECLARE 
@P_ID INT,@P_NAME NVARCHAR(250),@PRICE DECIMAL(10,2)
OPEN CUR_SELECT
FETCH NEXT FROM CUR_SELECT INTO @P_ID,@P_NAME,@PRICE
	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT 'ID :: '+CAST(@P_ID AS VARCHAR)+' NAME :: '+@P_NAME+' PRICE :: '+CAST(@PRICE AS VARCHAR)
		FETCH NEXT FROM CUR_SELECT INTO @P_ID,@P_NAME,@PRICE
	END
CLOSE CUR_SELECT
DEALLOCATE CUR_SELECT

-- 2.
DECLARE CUR_SELECT1 CURSOR
FOR SELECT PRODUCT_ID, PRODUCT_NAME FROM PRODUCTS
DECLARE 
@PRO_ID INT,@PRO_NAME NVARCHAR(250)
OPEN CUR_SELECT1
FETCH NEXT FROM CUR_SELECT1 INTO @PRO_ID,@PRO_NAME
	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT CAST(@PRO_ID AS VARCHAR)+' _ '+@PRO_NAME
		FETCH NEXT FROM CUR_SELECT1 INTO @PRO_ID,@PRO_NAME
	END
CLOSE CUR_SELECT1
DEALLOCATE CUR_SELECT1

-- 3.
DECLARE CUR_SELECT2 CURSOR
FOR SELECT PRICE, PRODUCT_NAME FROM PRODUCTS
DECLARE 
@P_PRICE DECIMAL(10,2),@P_PNAME NVARCHAR(250)
OPEN CUR_SELECT2
FETCH NEXT FROM CUR_SELECT2 INTO @P_PRICE , @P_PNAME
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @P_PRICE > 30000
		BEGIN
			PRINT 'PRODUCT NAME :: '+CAST(@P_PNAME AS VARCHAR) 
		END
		FETCH NEXT FROM CUR_SELECT2 INTO @P_PRICE, @P_PNAME
	END
CLOSE CUR_SELECT2
DEALLOCATE CUR_SELECT2

-- 4. 
DECLARE CUR_DEL CURSOR
FOR SELECT PRODUCT_ID FROM PRODUCTS
DECLARE 
@PID INT
OPEN CUR_DEL
FETCH NEXT FROM CUR_DEL INTO @PID
	WHILE @@FETCH_STATUS = 0
	BEGIN
		DELETE FROM PRODUCTS WHERE PRODUCT_ID=@PID
		FETCH NEXT FROM CUR_DEL INTO @PID
	END
CLOSE CUR_DEL
DEALLOCATE CUR_DEL

----------------------------------------------------------------------
-- PART B
-- 1.
DECLARE MODIFY_CUR CURSOR
FOR SELECT PRODUCT_ID, PRODUCT_NAME,PRICE FROM PRODUCTS
DECLARE 
@PID1 INT,@PNAME1 NVARCHAR(250),@PRICE1 DECIMAL(10,2)
OPEN MODIFY_CUR
FETCH NEXT FROM MODIFY_CUR INTO @PID1,@PNAME1,@PRICE1
	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE PRODUCTS SET @PRICE1 = @PRICE1 * 1.1
		PRINT 'ID :: '+CAST(@PID1 AS VARCHAR)+' NAME :: '+@PNAME1+' PRICE :: '+CAST(@PRICE1 AS VARCHAR)
		FETCH NEXT FROM MODIFY_CUR INTO @PID1,@PNAME1,@PRICE1
	END
CLOSE MODIFY_CUR
DEALLOCATE MODIFY_CUR

-- 2.
DECLARE MODIFY_CUR1 CURSOR
FOR SELECT PRODUCT_ID, PRODUCT_NAME,PRICE FROM PRODUCTS
DECLARE 
@PID2 INT,@PNAME2 NVARCHAR(250),@PRICE2 DECIMAL(10,2)
OPEN MODIFY_CUR1
FETCH NEXT FROM MODIFY_CUR1 INTO @PID2,@PNAME2,@PRICE2
	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT 'ROUNDED PRICE OF '+CAST(@PID2 AS VARCHAR)+' : '+CAST(FLOOR(@PRICE2)AS VARCHAR)
		FETCH NEXT FROM MODIFY_CUR1 INTO @PID2,@PNAME2,@PRICE2
	END
CLOSE MODIFY_CUR1
DEALLOCATE MODIFY_CUR1

----------------------------------------------------------------------
-- PART C
-- 1.

CREATE TABLE NEW_PRODUCTS(
	PRO_ID INT PRIMARY KEY,
	PRO_NAME NVARCHAR(250) NOT NULL,
	PRO_PRICE DECIMAL(10,2) NOT NULL,
)

DECLARE INSERT_CUR1 CURSOR
FOR SELECT PRODUCT_ID, PRODUCT_NAME,PRICE FROM PRODUCTS
DECLARE 
@PDT_ID INT,@PDT_NAME NVARCHAR(250),@PDT_PRICE DECIMAL(10,2)
OPEN INSERT_CUR1
FETCH NEXT FROM INSERT_CUR1 INTO @PDT_ID,@PDT_NAME,@PDT_PRICE
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(@PDT_NAME='LAPTOP')
		BEGIN
			INSERT INTO NEW_PRODUCTS VALUES (@PDT_ID,@PDT_NAME,@PDT_PRICE) 
		END
		FETCH NEXT FROM INSERT_CUR1 INTO @PDT_ID,@PDT_NAME,@PDT_PRICE
	END
CLOSE INSERT_CUR1
DEALLOCATE INSERT_CUR1

-- 2.
CREATE TABLE ArchivedProducts(
	H_PRO_ID INT PRIMARY KEY,
	H_PRO_NAME NVARCHAR(250) NOT NULL,
	H_PRO_PRICE DECIMAL(10,2) NOT NULL
)


DECLARE INSERT_CUR2 CURSOR
FOR SELECT PRODUCT_ID, PRODUCT_NAME,PRICE FROM PRODUCTS
DECLARE 
@PDT_ID1 INT,@PDT_NAME1 NVARCHAR(250),@PDT_PRICE1 DECIMAL(10,2)
OPEN INSERT_CUR2
FETCH NEXT FROM INSERT_CUR2 INTO @PDT_ID1,@PDT_NAME1,@PDT_PRICE1
	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(@PDT_PRICE1>50000)
		BEGIN
			INSERT INTO ArchivedProducts VALUES (@PDT_ID1,@PDT_NAME1,@PDT_PRICE1) 
			DELETE FROM PRODUCTS WHERE PRODUCT_ID=@PDT_ID1
		END
		FETCH NEXT FROM INSERT_CUR2 INTO @PDT_ID1,@PDT_NAME1,@PDT_PRICE1
	END
CLOSE INSERT_CUR2
DEALLOCATE INSERT_CUR2
----------------------------------------------------------------------