

--MATH FUNCTIONS

--PART :: A
--1.
SELECT ( 5 * 30 )
--2.
SELECT ABS(-25) , ABS(25) , ABS(-50) , ABS(50)
--3.
SELECT CEILING(25.2) , CEILING(25.7) , CEILING(-25.2) 
--4.
SELECT FLOOR(25.2) , FLOOR(25.7) , FLOOR(-25.2)
--5.
SELECT ( 5 % 2 ) , ( 5 % 3 )
--6.
SELECT POWER( 3 , 2 ) , POWER( 4 , 3 )
--7.
SELECT SQRT(25) , SQRT(30) , SQRT(50)
--8.
SELECT SQUARE(5) , SQUARE(15) , SQUARE(25)
--9.
SELECT PI()
--10.
SELECT ROUND(157.732 , -2) , ROUND(157.732 , 0) , ROUND(157.732 , 2)
--11.
SELECT EXP(2) , EXP(3)
--12.
SELECT LOG10(2)
--13.
SELECT LOG10(5) , LOG10(100)
--14.
SELECT SIN(3.1415) , COS(3.1415) , TAN(3.1415)
--15.
SELECT SIGN(-25) , SIGN(0) , SIGN(25)
--16.
SELECT RAND()



--PART :: B

CREATE TABLE EMP_MASTER(
	EMPNO INT,
	EMPNAME VARCHAR(20),
	JOININGDATE DATE,
	SALARY DECIMAL(10,2),
	COMMISSION DECIMAL(10,2),
	CITY VARCHAR(20),
	DEPTCODE VARCHAR(10)
)
INSERT INTO EMP_MASTER 
VALUES
(101, 'KEYUR', '2002-01-05', 12000, 4500, 'RAJKOT', '3@g')
,(102, 'HARDIK', '2004-02-15', 14000, 2500, 'AHMEDABAD', '3@')
,(103, 'KAJAL', '2006-03-14', 15000, 3000, 'BARODA', '3-GD')
,(104, 'BHOOMI', '2005-06-23', 12500, 1000, 'AHMEDABAD', '1A3D')
,(105, 'HARMIT', '2004-02-15', 14000, 2000, 'RAJKOT', '312A')
SELECT * FROM EMP_MASTER

--1.
SELECT SALARY, (SALARY + COMMISSION) AS 'SALARY + COMMISSION' FROM EMP_MASTER
--2.
SELECT CEILING(55.2) AS '55.2', CEILING(35.7) AS '35.7', CEILING(-55.2) AS '-55.2'
--3.
SELECT FLOOR(55.2) AS '55.2', FLOOR(35.7) AS '35.7', FLOOR(-55.2) AS '-55.2'
--4.
SELECT (55%2) AS '55', (55%3) AS '55'
--5.
SELECT POWER(23,2) , POWER(14,3)



--PART :: C
--1.
SELECT * FROM EMP_MASTER WHERE (SALARY + COMMISSION) > 15000
--2.
SELECT * FROM EMP_MASTER WHERE COMMISSION > 0.25 * SALARY
--3.
SELECT * FROM EMP_MASTER WHERE YEAR(JOININGDATE) > 2005 AND (SALARY + COMMISSION) > 15000
--4.
SELECT * FROM EMP_MASTER WHERE (SALARY + COMMISSION) >= SALARY * 2



--STRING FUNCTIONS

--PART :: A
--1.
SELECT LEN(NULL) , LEN('   HELLO     ') , LEN(' BLANK')
--2.
SELECT LOWER('GAUTAM') , UPPER('gautam')
--3.
SELECT LEFT('GAUTAM' , 3)
--4.
SELECT SUBSTRING('GAUTAMJOGI' , 3 , 10)
--5.
SELECT REPLACE('ABC123EFG' , '123' , 'XYZ') , REPLACE('ABCABCABC' , 'C' , '5')
--6.
SELECT ASCII('a') , ASCII('A') , ASCII('z') , ASCII('Z') , ASCII(0) , ASCII(9)
--7.
SELECT CHAR(97) , CHAR(65) , CHAR(122) , CHAR(90) , CHAR(48) , CHAR(57)
--8.
SELECT LTRIM(' hello world  ')
--9.
SELECT RTRIM(' hello world  ')
--10.
SELECT SUBSTRING('SQL SERVER' , 1 , 4) , SUBSTRING('SQL SERVER' , LEN('SQL Server') - 4 , 5)
--11.
SELECT CAST('1234.56' AS DECIMAL) , CONVERT(DECIMAL , '1234.56')
--12.
SELECT CAST(10.58 AS INT) , CONVERT(INT , 10.8)
--13.
SELECT SPACE(10) + 'GAUTAM'
--14.
SELECT CONCAT('GAUTAM' , 'JOGI') , 'GAUTAM' + 'JOGI'
--15.
SELECT REVERSE('DARSHAN')
--16.
SELECT REPLICATE('GAUTAM' , 3)



--PART :: B
--1.
SELECT LEN(EMPNAME) AS 'LENGTH OF NAME', LEN(CITY) AS 'LENGTH OF CITY' FROM EMP_MASTER
--2.
SELECT UPPER(EMPNAME) AS 'UPPERCASE', LOWER(EMPNAME) AS 'LOWERCASE', UPPER(CITY) AS 'CITY IN UPPERCASE', LOWER(CITY) AS 'CITY IN UPPERCASE' FROM EMP_MASTER
--3.
SELECT SUBSTRING(EMPNAME,1,1) AS 'FIRST CHARACTER OF NAME' FROM EMP_MASTER
--4.
SELECT SUBSTRING(CITY,3,10) FROM EMP_MASTER
--5.
SELECT LEFT(EMPNAME,4) , RIGHT(EMPNAME,5) FROM EMP_MASTER



--PART :: C
--1.
SELECT '          ' + EMPNAME FROM EMP_MASTER
SELECT CONCAT('          ',EMPNAME) FROM EMP_MASTER
--2.
SELECT EMPNAME + ' ' + CITY AS 'EMPNAME + CITY' FROM EMP_MASTER
SELECT CONCAT(EMPNAME, ' ', CITY) AS 'EMPNAME + CITY' FROM EMP_MASTER
--3.
SELECT  CAST(EMPNO AS VARCHAR) + ' ' + EMPNAME + ' ' + CAST(JOININGDATE AS VARCHAR) + ' ' + CAST(SALARY AS VARCHAR) + ' ' + CAST(COMMISSION AS VARCHAR) + ' ' + CITY + ' ' + DEPTCODE AS 'After Combine All Colums' FROM EMP_MASTER
SELECT CONCAT(EMPNO, ' ', EMPNAME, ' ', JOININGDATE, ' ', SALARY, ' ', COMMISSION, ' ', CITY, ' ', DEPTCODE) FROM EMP_MASTER
SELECT CONCAT_WS(' ', EMPNO, EMPNAME, JOININGDATE, SALARY, COMMISSION, CITY, DEPTCODE) FROM EMP_MASTER
--4.
SELECT EMPNAME + ' LIVES IN ' + CITY AS '<EMPNAME> LIVES IN <CITY>' FROM EMP_MASTER
SELECT CONCAT(EMPNAME, ' LIVES IN ', CITY) AS '<EMPNAME> LIVES IN <CITY>' FROM EMP_MASTER
--5.
SELECT 'EMP NO OF ' + EMPNAME + ' IS ' + CAST(EMPNO AS VARCHAR) AS 'EMP NO OF <EMPNAME> IS <EMPNO>' FROM EMP_MASTER
SELECT CONCAT('EMP NO OF ', EMPNAME, ' IS ', EMPNO) AS 'EMP NO OF <EMPNAME> IS <EMPNO>' FROM EMP_MASTER
--6.
SELECT EMPNAME FROM EMP_MASTER WHERE SUBSTRING(EMPNAME,3,1) IN ('A', 'E', 'I', 'O', 'U')
--7.
SELECT EMPNAME + ' ' + CITY AS 'EMPNAME + CITY' FROM EMP_MASTER WHERE RIGHT(EMPNAME, 1) = 'R' AND LEFT(CITY, 1) = 'R'
SELECT CONCAT(EMPNAME, ' ', CITY) AS 'EMPNAME + CITY' FROM EMP_MASTER WHERE RIGHT(EMPNAME, 1) = 'R' AND LEFT(CITY, 1) = 'R'



--DATE FUNCTIONS

--PART :: A
--1.
SELECT GETDATE() AS 'TODAY_DATE'
--2.
SELECT DATEADD(DAY , 365 , GETDATE())
--3.
SELECT FORMAT(GETDATE() , 'MMMM dd yyyy HH:MM')
--4.
SELECT FORMAT(GETDATE() , 'dd MMM yyyy')
--5.
SELECT FORMAT(GETDATE() , 'MMM dd, yy')
--6.
SELECT DATEDIFF(MONTH , '31-DEC-08' , '31-MAR-09')
--7.
SELECT DATEDIFF(HOUR , '25-Jan-12 7:00' , '26-Jan-12 10:30')
--8.
SELECT DATENAME(DAY , '12-MAY-16') , DATENAME(MONTH , '12-MAY-16') , DATENAME(YEAR , '12-MAY-16')
--9.
SELECT DATEADD(YEAR , 5 , GETDATE())
--10.
SELECT DATEADD(MONTH , -2 , GETDATE())
--11.
SELECT DATENAME(MONTH , GETDATE()) , DATEPART(MONTH , GETDATE())
--12.
SELECT DATENAME(DAY , EOMONTH(GETDATE()))
--13.
SELECT DATEDIFF(YEAR , '2007/01/22' , GETDATE()) , DATEDIFF(MONTH, '2007/01/22' , GETDATE())



--Part :: B
--1.
SELECT DATEADD(DAY, 365, JOININGDATE) FROM EMP_MASTER
--2.
SELECT DATEDIFF(MONTH, JOININGDATE, '2009-03-31') FROM EMP_MASTER
--3.
SELECT DATEDIFF(YEAR, JOININGDATE, '2010-9-14') FROM EMP_MASTER



--Part :: C
--1.
SELECT DATENAME(DAY, JOININGDATE) AS 'DAY', DATENAME(MONTH, JOININGDATE) AS 'MONTH' , DATENAME(YEAR, JOININGDATE) AS 'YEAR' FROM EMP_MASTER
--2.
SELECT DATEADD(YEAR, 5, JOININGDATE) AS 'ADDS 5 YEARS TO JOININGDATE' FROM EMP_MASTER
--3.
SELECT DATEADD(MONTH, -2, JOININGDATE) AS 'SUBTRACT 2 MONTHS FROM JOININGDATE' FROM EMP_MASTER
--4.
SELECT DATENAME(MONTH, JOININGDATE) AS 'MONTH' FROM EMP_MASTER
SELECT DATEPART(MONTH, JOININGDATE) AS 'MONTH' FROM EMP_MASTER
--5.
SELECT * FROM EMP_MASTER WHERE CAST(DATENAME(DAY, JOININGDATE) AS INT) BETWEEN 1 AND 15
--6.
SELECT * FROM EMP_MASTER WHERE DATENAME(DAY, JOININGDATE) = DATENAME(DAY, EOMONTH(JOININGDATE, 1))
--7.
SELECT * FROM EMP_MASTER WHERE DATENAME(YEAR, JOININGDATE) % 4 = 0 AND DATENAME(YEAR, JOININGDATE) % 100 != 0 OR DATENAME(YEAR, JOININGDATE) % 400 = 0 